2024-11-08 13:03:14,007 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-09 08:22:09,809 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-09 08:24:47,854 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-09 08:25:19,829 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-09 08:25:48,813 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-09 08:37:23,901 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-09 08:57:41,267 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-09 08:58:51,883 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-09 08:59:19,014 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-09 09:02:24,150 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-09 09:02:57,485 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-09 09:04:19,958 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-09 09:29:52,623 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-09 09:32:28,321 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-09 09:35:17,833 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-09 09:45:53,480 ERROR: Exception on /chat/3 [GET] [in C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py", line 883, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py", line 902, in finalize_request
    response = self.make_response(rv)
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py", line 1174, in make_response
    raise TypeError(
TypeError: The view function for 'chat' did not return a valid response. The function either returned None or ended without a return statement.
2024-11-09 09:46:00,458 ERROR: Exception on /chat/3 [GET] [in C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py", line 883, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py", line 902, in finalize_request
    response = self.make_response(rv)
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py", line 1174, in make_response
    raise TypeError(
TypeError: The view function for 'chat' did not return a valid response. The function either returned None or ended without a return statement.
2024-11-12 10:35:50,366 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-12 16:23:08,056 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-12 16:45:11,595 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-14 13:38:39,981 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-14 13:43:59,976 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-14 13:45:43,777 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-14 14:10:12,490 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-14 14:10:19,075 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-14 14:10:40,770 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-14 14:17:03,134 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-14 14:25:04,658 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-14 14:26:31,354 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-14 14:31:40,472 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-14 14:40:52,559 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-14 14:41:27,447 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-14 14:41:42,877 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-14 14:41:59,585 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-14 14:42:15,199 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-14 14:42:27,204 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-14 14:43:00,432 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-14 14:46:15,661 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-14 14:52:24,284 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-14 14:52:26,601 ERROR: Exception on /user/prokivan [GET] [in C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\pycharm\Finall_Project\app\routes.py", line 110, in user
    return render_template('user.html', user=user, posts=posts.items,
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\pycharm\Finall_Project\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\pycharm\Finall_Project\app\templates\base.html", line 40, in top-level template code
    {% block content %}{% endblock %}
  File "C:\pycharm\Finall_Project\app\templates\user.html", line 34, in block 'content'
    {% if chat_info.unread_count > 0 %}
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\jinja2\environment.py", line 487, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'chat_info' is undefined
2024-11-14 14:52:34,926 ERROR: Exception on /user/prokivan [GET] [in C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\pycharm\Finall_Project\app\routes.py", line 110, in user
    return render_template('user.html', user=user, posts=posts.items,
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\pycharm\Finall_Project\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\pycharm\Finall_Project\app\templates\base.html", line 40, in top-level template code
    {% block content %}{% endblock %}
  File "C:\pycharm\Finall_Project\app\templates\user.html", line 34, in block 'content'
    {% if chat_info.unread_count > 0 %}
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\jinja2\environment.py", line 487, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'chat_info' is undefined
2024-11-14 14:52:59,481 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-14 15:05:10,911 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-14 18:26:03,258 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-14 18:43:49,357 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
