2024-11-07 14:51:11,532 ERROR: Exception on /index [GET] [in C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\pycharm\Finall_Project\app\routes.py", line 30, in index
    return render_template('index.html', title='Home', form=form,
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\jinja2\environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\jinja2\environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\jinja2\environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\pycharm\Finall_Project\app\templates\index.html", line 31, in template
    {% block content %}
jinja2.exceptions.TemplateAssertionError: block 'content' defined twice
2024-11-07 14:51:19,494 ERROR: Exception on /index [GET] [in C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\pycharm\Finall_Project\app\routes.py", line 30, in index
    return render_template('index.html', title='Home', form=form,
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\jinja2\environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\jinja2\environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\jinja2\environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\pycharm\Finall_Project\app\templates\index.html", line 31, in template
    {% block content %}
jinja2.exceptions.TemplateAssertionError: block 'content' defined twice
2024-11-07 14:51:20,204 ERROR: Exception on /explore [GET] [in C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\pycharm\Finall_Project\app\routes.py", line 63, in explore
    return render_template('index.html', title='Explore', posts=posts.items,
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\jinja2\environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\jinja2\environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\jinja2\environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\pycharm\Finall_Project\app\templates\index.html", line 31, in template
    {% block content %}
jinja2.exceptions.TemplateAssertionError: block 'content' defined twice
2024-11-07 14:53:32,048 INFO: Blog startup [in C:\pycharm\Finall_Project\app\__init__.py:31]
2024-11-07 14:53:38,407 ERROR: Exception on /index [GET] [in C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\pycharm\Finall_Project\app\routes.py", line 30, in index
    return render_template('index.html', title='Home', form=form,
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\pycharm\Finall_Project\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\pycharm\Finall_Project\app\templates\base.html", line 34, in top-level template code
    {% block content %}{% endblock %}
  File "C:\pycharm\Finall_Project\app\templates\index.html", line 8, in block 'content'
    {{ form.username.label }}<br>
  File "C:\pycharm\Finall_Project\venv\lib\site-packages\jinja2\environment.py", line 487, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.forms.PostForm object' has no attribute 'username'
